FROM node:18-alpine as deps-prod
WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

FROM node:18-alpine as build
WORKDIR /app

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:18-alpine as runner
WORKDIR /app

COPY --from=deps-prod /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./

RUN chown -R node:node /app
USER node

####
EXPOSE 3001
CMD ["node", "dist/main"]