
#Это называется ступенчатая сборка



#Общая сборка - донор!
FROM node:18-alpine AS base
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build


#сборка dev
FROM node:18-alpine AS dev
WORKDIR /app
COPY package*.json ./
COPY --from=base /app/node_modules ./node_modules
COPY . .

RUN chown -R node:node /app
USER node
####
EXPOSE 3000
CMD ["npm", "run", "start:dev"]


#сборка build
FROM node:18-alpine AS production
WORKDIR /app

COPY --from=base /app/package*.json ./
RUN npm ci --only=production && npm cache clean --force
COPY --from=base /app/dist ./dist


#Это необходимо для безопасности!
# Создаём пользователя "node"
# чтобы не иметь root прав

RUN chown -R node:node /app
USER node

####
EXPOSE 3000
CMD ["node", "dist/main"]